import Head from 'next/head'


export default function Home() {

  const post = [
    {title: 'React Testing', excerpt: 'Learn React Testing'},
    {title: 'Welcome to God', excerpt: 'Welcome to God House, Pray my boy'}
  ]

  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        {post.map((post, index) => (
          // eslint-disable-next-line react/jsx-key
          <div>
            {post.title}
            {post.excerpt}
          </div>  
        ))}
      </div>
      

      
    </div>
  )
}
