import Head from 'next/head'
import {PostCard, PostWidget, Categories} from '../components/index'


export default function Home() {

  const post = [
    {title: 'React Testing', excerpt: 'Learn React Testing'},
    {title: 'Welcome to God', excerpt: 'Welcome to God House, Pray my boy'}
  ]

  return (
    <div className='container mx-auto px-10 mb-8 bg-gray-400'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {post.map((post) => (
            <PostCard post={post} key={post.title} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relative top-8">
               <PostWidget />
               <Categories />
            </div>
        </div>
      </div>
      

      
    </div>
  )
}
